[workspace]
members = [
	"asset-registry",
	"auction",
	"authority",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/runtime-api",
	"tokens",
	"tokens/runtime-api",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"payments",
	"parameters",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[workspace.dependencies]
log = { version = "0.4.20", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.189" }
parity-scale-codec = { version = "3.6.5", default-features = false, features = ["max-encoded-len"] }

frame-benchmarking = { version = "24.0.0", default-features = false }
frame-support = { version = "24.0.0", default-features = false }
frame-system = { version = "24.0.0", default-features = false }
pallet-authority-discovery = { version = "24.0.0", default-features = false }
pallet-authorship = { version = "24.0.0", default-features = false }
pallet-babe = { version = "24.0.0", default-features = false }
pallet-balances = { version = "24.0.0", default-features = false }
pallet-elections-phragmen = { version = "25.0.0", default-features = false }
pallet-message-queue = { version = "27.0.0", default-features = false }
pallet-scheduler = { version = "25.0.0", default-features = false }
pallet-session = { version = "24.0.0", default-features = false }
pallet-staking = { version = "24.0.0", default-features = false }
pallet-timestamp = { version = "23.0.0", default-features = false }
pallet-treasury = { version = "23.0.0", default-features = false }
pallet-vesting = { version = "24.0.0", default-features = false }
pallet-transaction-payment = { version = "24.0.0", default-features = false }
pallet-preimage = { version = "24.0.0", default-features = false }
# pallet-root-testing = { version = "*", default-features = false }
sp-api = { version = "22.0.0", default-features = false }
sp-application-crypto = { version = "26.0.0", default-features = false }
sp-arithmetic = { version = "19.0.0", default-features = false }
sp-authority-discovery = { version = "22.0.0", default-features = false }
sp-blockchain = { version = "24.0.0", default-features = false }
sp-consensus = { version = "0.28.0", default-features = false }
sp-consensus-slots = { version = "0.28.0", default-features = false }
sp-core = { version = "24.0.0", default-features = false }
sp-debug-derive = { version = "11.0.0", default-features = false }
sp-externalities = { version = "0.22.0", default-features = false }
sp-inherents = { version = "22.0.0", default-features = false }
sp-io = { version = "26.0.0", default-features = false }
sp-keystore = { version = "0.30.0", default-features = false }
sp-npos-elections = { version = "22.0.0", default-features = false }
sp-panic-handler = { version = "11.0.0", default-features = false }
sp-runtime = { version = "27.0.0", default-features = false }
sp-runtime-interface = { version = "20.0.0", default-features = false }
sp-session = { version = "23.0.0", default-features = false }
sp-staking = { version = "22.0.0", default-features = false }
sp-state-machine = { version = "0.31.0", default-features = false }
sp-std = { version = "11.0.0", default-features = false }
sp-storage = { version = "16.0.0", default-features = false }
sp-timestamp = { version = "22.0.0", default-features = false }
sp-trie = { version = "25.0.0", default-features = false }
sp-version = { version = "25.0.0", default-features = false }
sp-wasm-interface = { version = "17.0.0", default-features = false }
sp-tracing = { version = "13.0.0", default-features = false }
sp-maybe-compressed-blob = { version = "8.0.0", default-features = false }
sp-weights = { version = "23.0.0", default-features = false }
cumulus-primitives-core = { version = "0.3.0", default-features = false }
cumulus-pallet-dmp-queue = { version = "0.3.0", default-features = false }
cumulus-pallet-xcmp-queue = { version = "0.3.0", default-features = false }
cumulus-pallet-xcm = { version = "0.3.0", default-features = false }
parachain-info = { package = "staging-parachain-info", version = "0.3.0", default-features = false }
pallet-xcm = { version = "3.0.0", default-features = false }
polkadot-core-primitives = { version = "3.0.0", default-features = false }
polkadot-runtime-parachains = { version = "3.0.0", default-features = false }
polkadot-parachain-primitives = { version = "2.0.0", default-features = false }
polkadot-primitives = { version = "3.0.0", default-features = false }
xcm = { package = "staging-xcm", version = "3.0.1", default-features = false }
xcm-executor = { package = "staging-xcm-executor", version = "3.0.0", default-features = false }
xcm-builder = { package = "staging-xcm-builder", version = "3.0.1", default-features = false }

xcm-simulator = { version = "3.0.0" }
sc-client-api = { version = "24.0.0" }
sc-client-db = { version = "0.31.0" }
sc-executor = { version = "0.28.0" }
sc-executor-common = { version = "0.25.0" }
sc-utils = { version = "10.0.0" }
